import {
  AutumnEvents,
  Elements,
  Events,
  SpringEvents,
  SummerEvents,
  WinterEvents,
} from "../types";

const probabilityEventByElement: Record<Events, Record<Elements, number>> = {
  Earthquake: {
    Dark: 0,
    Electro: 0,
    Fire: 0,
    Ice: 0,
    Light: 0,
    Parasite: 0,
    Metal: 1,
    Water: 0,
    Wind: 0.5,
  },
  Volcano: {
    Dark: 0,
    Electro: 0,
    Fire: 1,
    Ice: -0.4,
    Light: 0,
    Parasite: 0,
    Metal: 0.4,
    Water: -0.2,
    Wind: 0,
  },
  Hurricanes: {
    Dark: 0.4,
    Electro: 0.5,
    Fire: -0.4,
    Ice: 0.4,
    Light: -0.2,
    Parasite: 0,
    Metal: 0,
    Water: 0.5,
    Wind: 0.5,
  },
  Thunderstorm: {
    Dark: 1,
    Electro: 1,
    Fire: 0,
    Ice: 0,
    Light: -0.2,
    Parasite: 0,
    Metal: -0.2,
    Water: 0.1,
    Wind: 0,
  },
  Tsunami: {
    Dark: 0.2,
    Electro: 0,
    Fire: -0.4,
    Ice: 0.3,
    Light: -0.2,
    Parasite: 0,
    Metal: -0.6,
    Water: 0.6,
    Wind: 0,
  },
  Tornado: {
    Dark: 0.5,
    Electro: 0.5,
    Fire: 0,
    Ice: 0,
    Light: -0.4,
    Parasite: 0,
    Metal: 0,
    Water: 0.2,
    Wind: 1,
  },
  Flood: {
    Dark: 0,
    Electro: 0,
    Fire: 0,
    Ice: 0,
    Light: 0,
    Parasite: 0,
    Metal: -1,
    Water: 1,
    Wind: 0,
  },
  "Winter Storm": {
    Dark: 0,
    Electro: 0.5,
    Fire: -0.4,
    Ice: 0.6,
    Light: -0.2,
    Parasite: 0,
    Metal: 0,
    Water: 0,
    Wind: 0.5,
  },
  Rainy: {
    Dark: 0,
    Electro: 0,
    Fire: -0.3,
    Ice: 0,
    Light: 0,
    Parasite: 0,
    Metal: -0.3,
    Water: 1,
    Wind: 0,
  },
  Sunny: {
    Dark: 0,
    Electro: 0,
    Fire: 0.6,
    Ice: 0,
    Light: 0,
    Parasite: 0,
    Metal: 0,
    Water: -0.3,
    Wind: 0,
  },
  Cloudy: {
    Dark: 0,
    Electro: 0,
    Fire: 0,
    Ice: 0,
    Light: -0.1,
    Parasite: 0,
    Metal: 0,
    Water: 0,
    Wind: -0.5,
  },
  Windy: {
    Dark: 0,
    Electro: 0,
    Fire: 0,
    Ice: 0,
    Light: 0.2,
    Parasite: 0,
    Metal: 0,
    Water: 0,
    Wind: 0.5,
  },
  "Iron Rain": {
    Dark: 0,
    Electro: 0,
    Fire: 0,
    Ice: 0,
    Light: 0,
    Parasite: 0,
    Metal: 1.2,
    Water: 0.4,
    Wind: 0,
  },
  Moonlight: {
    Dark: 4,
    Electro: 0,
    Fire: 0,
    Ice: 0,
    Light: 0,
    Parasite: 0,
    Metal: 0,
    Water: 0,
    Wind: 0,
  },
  Malaria: {
    Dark: 0,
    Electro: 0,
    Fire: 0,
    Ice: 0,
    Light: 0,
    Parasite: 1,
    Metal: 0,
    Water: 0,
    Wind: 0,
  },
  "Heat Wave": {
    Dark: 0.1,
    Electro: 0,
    Fire: 1,
    Ice: -0.6,
    Light: 0.2,
    Parasite: 0,
    Metal: 0,
    Water: -0.3,
    Wind: 0,
  },
  "Locusts Swarm": {
    Dark: 0,
    Electro: 0,
    Fire: 0,
    Ice: 0,
    Light: 0,
    Parasite: 1,
    Metal: 0,
    Water: 0,
    Wind: 0,
  },
  "Rats Swarm": {
    Dark: 0,
    Electro: 0,
    Fire: 0,
    Ice: 0,
    Light: 0,
    Parasite: 1,
    Metal: 0,
    Water: 0,
    Wind: 0,
  },
  "Coronal Mass Ejection": {
    Dark: 0,
    Electro: 0,
    Fire: 0.4,
    Ice: 0,
    Light: 1,
    Parasite: 0,
    Metal: 0,
    Water: 0,
    Wind: 0,
  },
  "Solar Flares": {
    Dark: 0,
    Electro: 0,
    Fire: 0.8,
    Ice: 0,
    Light: 0.8,
    Parasite: 0,
    Metal: 0,
    Water: 0,
    Wind: 0,
  },
  "Solar Maxima": {
    Dark: 0,
    Electro: 0,
    Fire: 0.4,
    Ice: 0,
    Light: 1,
    Parasite: 0,
    Metal: 0,
    Water: 0,
    Wind: 0,
  },
  "Proton Storm": {
    Dark: 0,
    Electro: 0,
    Fire: 0,
    Ice: 0,
    Light: 2,
    Parasite: 0,
    Metal: 0,
    Water: 0,
    Wind: 0,
  },
  Snowy: {
    Dark: 0,
    Electro: 0,
    Fire: -0.4,
    Ice: 1,
    Light: 0,
    Parasite: 0,
    Metal: 0,
    Water: 0.6,
    Wind: 0,
  },
  "Cold Wave": {
    Dark: 0,
    Electro: 0,
    Fire: -0.6,
    Ice: 1.2,
    Light: 0,
    Parasite: 0,
    Metal: 0,
    Water: 0,
    Wind: 0,
  },
  "Magnetic Reconnection": {
    Dark: 0,
    Electro: 0.5,
    Fire: 0,
    Ice: 0,
    Light: 0,
    Parasite: 0,
    Metal: 0.5,
    Water: 0,
    Wind: 0,
  },
};

const winterEventProbabilityByElement: Record<
  WinterEvents,
  Record<Elements, number>
> = {
  Volcano: probabilityEventByElement.Volcano,
  Earthquake: probabilityEventByElement.Earthquake,
  Snowy: probabilityEventByElement.Snowy,
  "Cold Wave": probabilityEventByElement["Cold Wave"],
  "Winter Storm": probabilityEventByElement["Winter Storm"],
  "Coronal Mass Ejection": probabilityEventByElement["Coronal Mass Ejection"],
  "Solar Flares": probabilityEventByElement["Solar Flares"],
  "Solar Maxima": probabilityEventByElement["Solar Maxima"],
  "Magnetic Reconnection": probabilityEventByElement["Magnetic Reconnection"],
  Windy: probabilityEventByElement.Windy,
};

const springEventProbabilityByElement: Record<
  SpringEvents,
  Record<Elements, number>
> = {
  Hurricanes: probabilityEventByElement.Hurricanes,
  Volcano: probabilityEventByElement.Volcano,
  Tsunami: probabilityEventByElement.Tsunami,
  Earthquake: probabilityEventByElement.Earthquake,
  Rainy: probabilityEventByElement.Rainy,
  Sunny: probabilityEventByElement.Sunny,
  Cloudy: probabilityEventByElement.Cloudy,
  "Iron Rain": probabilityEventByElement["Iron Rain"],
  "Locusts Swarm": probabilityEventByElement["Locusts Swarm"],
  "Rats Swarm": probabilityEventByElement["Rats Swarm"],
  Malaria: probabilityEventByElement.Malaria,
};

const summerEventProbabilityByElement: Record<
  SummerEvents,
  Record<Elements, number>
> = {
  "Heat Wave": probabilityEventByElement["Heat Wave"],
  Hurricanes: probabilityEventByElement.Hurricanes,
  Thunderstorm: probabilityEventByElement.Thunderstorm,
  Volcano: probabilityEventByElement.Volcano,
  Tsunami: probabilityEventByElement.Tsunami,
  Earthquake: probabilityEventByElement.Earthquake,
  Tornado: probabilityEventByElement.Tornado,
  Rainy: probabilityEventByElement.Rainy,
  Sunny: probabilityEventByElement.Sunny,
  Cloudy: probabilityEventByElement.Cloudy,
  "Locusts Swarm": probabilityEventByElement["Locusts Swarm"],
  "Rats Swarm": probabilityEventByElement["Rats Swarm"],
  Malaria: probabilityEventByElement.Malaria,
  "Coronal Mass Ejection": probabilityEventByElement["Coronal Mass Ejection"],
  "Solar Flares": probabilityEventByElement["Solar Flares"],
  "Solar Maxima": probabilityEventByElement["Solar Maxima"],
  "Proton Storm": probabilityEventByElement["Proton Storm"],
};

const autumnEventProbabilityByElement: Record<
  AutumnEvents,
  Record<Elements, number>
> = {
  Hurricanes: probabilityEventByElement.Hurricanes,
  Thunderstorm: probabilityEventByElement.Thunderstorm,
  Volcano: probabilityEventByElement.Volcano,
  Tsunami: probabilityEventByElement.Tsunami,
  Earthquake: probabilityEventByElement.Earthquake,
  Tornado: probabilityEventByElement.Tornado,
  Flood: probabilityEventByElement.Flood,
  "Winter Storm": probabilityEventByElement["Winter Storm"],
  Rainy: probabilityEventByElement.Rainy,
  Sunny: probabilityEventByElement.Sunny,
  Cloudy: probabilityEventByElement.Cloudy,
  Windy: probabilityEventByElement.Windy,
  "Iron Rain": probabilityEventByElement["Iron Rain"],
  Moonlight: probabilityEventByElement.Moonlight,
  "Locusts Swarm": probabilityEventByElement["Locusts Swarm"],
  "Rats Swarm": probabilityEventByElement["Rats Swarm"],
  Malaria: probabilityEventByElement.Malaria,
};

export const probabilityWeatherEventByElement = {
  Autumn: autumnEventProbabilityByElement,
  Springer: springEventProbabilityByElement,
  Summer: summerEventProbabilityByElement,
  Winter: winterEventProbabilityByElement,
};
